name: Run E2E Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DATABASE: api-solid
        ports:
          - '5432:5432'
        volumes:
          - postgres_data:/bitnami/postgresql

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'pnpm'

    - run: pnpm install

    - run: pnpm test:e2e

    env:
      JWT_SECRET: testing
      DATABASE_URL: "postgresql://docker:docker@localhost:5432/api-solid?schema=public"
