name: Run Unit Tests

on:
  push:
    branches:
      - '**'

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'pnpm'

    - run: pnpm install
    - name: Generate Prisma Client
      run: pnpm prisma generate
    - name: Run unit tests
      run: pnpm test
